name: test

on:
  push:
    branches: [ master ]

jobs:
  tag:
    runs-on: ubuntu-latest
    outputs:
      value: ${{ steps.export.outputs.tag }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set tag
        run: |
          ./tag
          git push origin --tags

      - name: Export tag for downstream use
        id: export
        run: |
          echo "tag=$(git describe --tags --abbrev=0)" >> "$GITHUB_OUTPUT"

  release:
    needs: [tag]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Image metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.ECR_REGISTRY }}/${{ matrix.command  }}
          tags: |
            type=sha,prefix=
            type=raw,prefix=,value=${{ env.IMAGE_TAG }}
        env:
          IMAGE_TAG: ${{ needs.tag.outputs.value }}
          ECR_REGISTRY: test
